### ISSUE TITLE
Add Serverless Framework support

### ISSUE THREAD

**Issue by lucasbastianik** [epsagon/clear-lambda-storage#1]
Hey 👋

I did a [repository](https://github.com/lucasbastianik/clear-lambda-storage-serverless) that use this project and Serverless framework to create a lambda that clear the Lambdas code storage.

You can schedule the Lambda code storage clean to run every period you want like code above:

```yaml
functions:
  clear_lambda_storage:
    handler: handler.clear_lambda_storage
    memorySize: 128
    timeout: 120
    events:
      - schedule: cron(0 12 ? * SUN *) # Run every sunday at 12:00pm UTC
```

Do you think that it's good to create a PR and increments this project here or maintains separately?

Happy serverless-ing ⚡!
